-- ═══════════════════════════════════════════════════════════
-- TEN80TEN — DATABASE SEED
-- Paste this into Supabase SQL Editor and click Run
-- UUIDs auto-generated by gen_random_uuid()
-- ═══════════════════════════════════════════════════════════

-- ─── TEAM MEMBERS ───

INSERT INTO team_members (name, email, role, secondary_role, status, joined_at) VALUES
  ('Aldridge Dagos', 'aldridge@ten80ten.com',    'owner',      'Approver / Developer',          'active', '2025-01-01'),
  ('Christer Umali', 'christer@ten80ten.com',    'admin',      'Approver',                      'active', '2025-02-01'),
  ('Alex Nicholson', 'alex@ten80ten.com',        'admin',      'Approver',                      'active', '2025-03-01'),
  ('Carlo Navarro',  'carlo@ten80ten.com',       'specialist', 'Creative Director / Approver',  'active', '2025-04-01'),
  ('Muaaz Saifi',    'muaaz.ten80ten@gmail.com', 'specialist', 'Social Media Specialist',       'active', '2025-05-01');

-- ─── POSTS (24 Kanban Cards) ───

-- Checklist templates
-- ck0 = all unchecked
-- ck2 = first 2 checked
-- ck3 = first 3 checked
-- ck4 = first 4 checked
-- ck5 = first 5 checked
-- ck6 = all 6 checked

INSERT INTO posts (title, stage, platforms, content_type, thumbnail_url, scheduled_date, scheduled_time, caption, hook, notes, checklist, created_at, updated_at) VALUES

-- ── IDEAS (4) ──
(
  'Sample Idea Post 1',
  'ideas',
  ARRAY['tiktok','instagram'],
  'reel',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  NULL, NULL,
  'This is a sample caption for idea post 1. Replace with your own content.',
  'Sample hook for idea 1...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":false},{"id":"2","label":"Caption proofread & hashtags added","checked":false},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-18T00:00:00Z', '2026-03-18T00:00:00Z'
),
(
  'Sample Idea Post 2',
  'ideas',
  ARRAY['facebook','instagram','youtube'],
  'video',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  NULL, NULL,
  'This is a sample caption for idea post 2. Replace with your own content.',
  'Sample hook for idea 2...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":false},{"id":"2","label":"Caption proofread & hashtags added","checked":false},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-17T00:00:00Z', '2026-03-17T00:00:00Z'
),
(
  'Sample Idea Post 3',
  'ideas',
  ARRAY['linkedin','facebook'],
  'carousel',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  NULL, NULL,
  'This is a sample caption for idea post 3. Replace with your own content.',
  'Sample hook for idea 3...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":false},{"id":"2","label":"Caption proofread & hashtags added","checked":false},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-16T00:00:00Z', '2026-03-16T00:00:00Z'
),
(
  'Sample Idea Post 4',
  'ideas',
  ARRAY['instagram','tiktok','linkedin'],
  'reel',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  NULL, NULL,
  'This is a sample caption for idea post 4. Replace with your own content.',
  'Sample hook for idea 4...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":false},{"id":"2","label":"Caption proofread & hashtags added","checked":false},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-15T00:00:00Z', '2026-03-15T00:00:00Z'
),

-- ── AWAITING APPROVAL (4) ──
(
  'Sample Awaiting Approval Post 1',
  'awaiting_approval',
  ARRAY['tiktok','facebook','instagram'],
  'video',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  '2026-03-24', '10:00',
  'This is a sample caption for an awaiting approval post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-12T00:00:00Z', '2026-03-20T00:00:00Z'
),
(
  'Sample Awaiting Approval Post 2',
  'awaiting_approval',
  ARRAY['facebook','youtube'],
  'video',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  '2026-03-25', '14:00',
  'This is a sample caption for an awaiting approval post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-10T00:00:00Z', '2026-03-19T00:00:00Z'
),
(
  'Sample Awaiting Approval Post 3',
  'awaiting_approval',
  ARRAY['instagram','linkedin','facebook'],
  'carousel',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  '2026-03-26', '09:00',
  'This is a sample caption for an awaiting approval post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-09T00:00:00Z', '2026-03-18T00:00:00Z'
),
(
  'Sample Awaiting Approval Post 4',
  'awaiting_approval',
  ARRAY['tiktok','instagram','youtube'],
  'reel',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  '2026-03-27', '12:00',
  'This is a sample caption for an awaiting approval post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-08T00:00:00Z', '2026-03-17T00:00:00Z'
),

-- ── REVISION NEEDED (4) ──
(
  'Sample Revision Post 1',
  'revision_needed',
  ARRAY['facebook','instagram','linkedin'],
  'image',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  '2026-03-23', '11:00',
  'This is a sample caption for a revision post. Replace with your own content.',
  'Sample hook...',
  'Reviewer: Please update the image and revise the CTA.',
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-06T00:00:00Z', '2026-03-20T00:00:00Z'
),
(
  'Sample Revision Post 2',
  'revision_needed',
  ARRAY['tiktok','youtube'],
  'video',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  '2026-03-24', '15:00',
  'This is a sample caption for a revision post. Replace with your own content.',
  'Sample hook...',
  'Reviewer: Audio track needs replacement with royalty-free music.',
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-05T00:00:00Z', '2026-03-19T00:00:00Z'
),
(
  'Sample Revision Post 3',
  'revision_needed',
  ARRAY['instagram','linkedin'],
  'carousel',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  '2026-03-25', '08:00',
  'This is a sample caption for a revision post. Replace with your own content.',
  'Sample hook...',
  'Reviewer: Fix typo on slide 3.',
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-04T00:00:00Z', '2026-03-18T00:00:00Z'
),
(
  'Sample Revision Post 4',
  'revision_needed',
  ARRAY['linkedin'],
  'carousel',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  '2026-03-28', '10:00',
  'This is a sample caption for a revision post. Replace with your own content.',
  'Sample hook...',
  'Reviewer: Verify the numbers and change format to document carousel.',
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":false},{"id":"4","label":"Call-to-action included","checked":false},{"id":"5","label":"Brand guidelines followed","checked":false},{"id":"6","label":"Scheduled date confirmed","checked":false}]',
  '2026-03-02T00:00:00Z', '2026-03-17T00:00:00Z'
),

-- ── APPROVED / SCHEDULED (4) ──
(
  'Sample Scheduled Post 1',
  'approved_scheduled',
  ARRAY['facebook','instagram','tiktok','linkedin'],
  'image',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  '2026-03-22', '09:00',
  'This is a sample caption for a scheduled post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-03-01T00:00:00Z', '2026-03-21T00:00:00Z'
),
(
  'Sample Scheduled Post 2',
  'approved_scheduled',
  ARRAY['instagram','facebook','tiktok'],
  'reel',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  '2026-03-23', '11:00',
  'This is a sample caption for a scheduled post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-03-02T00:00:00Z', '2026-03-20T00:00:00Z'
),
(
  'Sample Scheduled Post 3',
  'approved_scheduled',
  ARRAY['linkedin','instagram'],
  'video',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  '2026-03-26', '08:00',
  'This is a sample caption for a scheduled post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-03-05T00:00:00Z', '2026-03-21T00:00:00Z'
),
(
  'Sample Scheduled Post 4',
  'approved_scheduled',
  ARRAY['youtube','facebook'],
  'video',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  '2026-03-29', '14:00',
  'This is a sample caption for a scheduled post. Replace with your own content.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-03-08T00:00:00Z', '2026-03-21T00:00:00Z'
),

-- ── POSTED — RECENT (2) ──
(
  'Sample Posted Content 1',
  'posted',
  ARRAY['instagram','facebook'],
  'reel',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  '2026-03-15', '10:00',
  'This is a sample caption for a posted piece of content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-03-01T00:00:00Z', '2026-03-15T00:00:00Z'
),
(
  'Sample Posted Content 2',
  'posted',
  ARRAY['facebook','linkedin','youtube'],
  'video',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  '2026-03-12', '09:00',
  'This is a sample caption for a posted piece of content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-02-28T00:00:00Z', '2026-03-12T00:00:00Z'
),

-- ── POSTED — ARCHIVE (6, older than 7 days) ──
(
  'Sample Archive Post 1',
  'posted',
  ARRAY['facebook','instagram'],
  'video',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  '2026-01-10', '10:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2026-01-05T00:00:00Z', '2026-01-10T00:00:00Z'
),
(
  'Sample Archive Post 2',
  'posted',
  ARRAY['instagram','tiktok','youtube'],
  'reel',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  '2025-12-20', '12:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2025-12-15T00:00:00Z', '2025-12-20T00:00:00Z'
),
(
  'Sample Archive Post 3',
  'posted',
  ARRAY['facebook','instagram','tiktok'],
  'image',
  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop',
  '2025-11-28', '06:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2025-11-20T00:00:00Z', '2025-11-28T00:00:00Z'
),
(
  'Sample Archive Post 4',
  'posted',
  ARRAY['youtube','facebook'],
  'video',
  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop',
  '2025-10-15', '10:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2025-10-10T00:00:00Z', '2025-10-15T00:00:00Z'
),
(
  'Sample Archive Post 5',
  'posted',
  ARRAY['linkedin','facebook','instagram'],
  'carousel',
  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop',
  '2025-09-01', '09:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2025-08-25T00:00:00Z', '2025-09-01T00:00:00Z'
),
(
  'Sample Archive Post 6',
  'posted',
  ARRAY['instagram','facebook','linkedin','tiktok'],
  'reel',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop',
  '2025-08-15', '12:00',
  'Archived sample content. Replace with your own.',
  'Sample hook...',
  NULL,
  '[{"id":"1","label":"Thumbnail/cover image approved","checked":true},{"id":"2","label":"Caption proofread & hashtags added","checked":true},{"id":"3","label":"Hook verified (first 3 seconds)","checked":true},{"id":"4","label":"Call-to-action included","checked":true},{"id":"5","label":"Brand guidelines followed","checked":true},{"id":"6","label":"Scheduled date confirmed","checked":true}]',
  '2025-08-10T00:00:00Z', '2025-08-15T00:00:00Z'
);

-- ─── MEDIA ASSETS (6 sample files) ───

INSERT INTO media_assets (name, url, file_type, folder, added_by, used_in) VALUES
  ('sample-image-1.jpg',  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop', 'image', 'General',    'Aldridge', ARRAY[]::TEXT[]),
  ('sample-video-1.mp4',  'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&fit=crop', 'video', 'General',    'Christer', ARRAY[]::TEXT[]),
  ('sample-image-2.jpg',  'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=400&fit=crop', 'image', 'Marketing',  'Alex',     ARRAY[]::TEXT[]),
  ('sample-video-2.mp4',  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&fit=crop', 'video', 'Marketing',  'Carlo',    ARRAY[]::TEXT[]),
  ('sample-image-3.jpg',  'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400&fit=crop', 'image', 'Team',       'Muaaz',    ARRAY[]::TEXT[]);

-- ═══════════════════════════════════════════════════════════
-- SEED COMPLETE
-- 5 team members, 24 posts, 5 media assets
-- ═══════════════════════════════════════════════════════════
